### ISSUE TITLE
Bug with version 0.4.6

### ISSUE THREAD

**Issue by DominikProbst** [silvia-odwyer/lightbox.js#10]
Hi Silvia,
I installed the package in a new project of mine and with the latest version I receive an error.

![Bildschirmfoto 2023-03-23 um 21 06 10](https://user-images.githubusercontent.com/88315846/227339708-66a013a2-087c-484a-a466-d5a00d332999.png)

I tried every other version before 0.4.6 and the last one working for me are 0.3.9 & 0.4.5. So since 0.4.0 there maybe is a bug?

All I did in my NextJS component is to import these things:
`import {SlideshowLightbox, initLightboxJS} from "lightbox.js-react";`
`import 'lightbox.js-react/dist/index.css';`

**Comment by silvia-odwyer** [comment]
@DominikProbst Hi Dominik, 
Thanks for mentioning this bug, I've just released a new version of the library which should fix the issue.

This bug occurred because I added some demo product slider components with a Lightbox.js integration (using popular libraries such as Swiper etc), but it appears that the Swiper CSS can't be imported by Next.js using the current setup. I've removed these components for now and will perhaps create a new package for these demo components separately.

If the latest version release isn't working though, be sure to let me know and I'll take a look, thanks! 😄

**Comment by ebz8** [comment]
Hi, I just tried to install v.4 and got the following error :

"Could not find a declaration file for module 'lightbox.js-react'. '/Users/elodieboinzanchi/Sites/elbz_next/distributiondusensible/node_modules/lightbox.js-react/dist/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/lightbox.js-react` if it exists or add a new declaration (.d.ts) file containing `declare module 'lightbox.js-react';`ts(7016)"

I tried to install types but got "Not Found - GET https://registry.npmjs.org/@types%2flightbox.js-react - Not found". Any advice ? :)

**Comment by silvia-odwyer** [comment]
@ebz8 Hi there! Unfortunately Lightbox.js only supports React JavaScript projects for now. I'm currently working on the TypeScript version which will be released soon. 😄

**Comment by ebz8** [comment]
Hi Silvia, I only use Next.js without TypeScript (and no error with any other library)... I don't understand what's the pb here.

**Comment by silvia-odwyer** [comment]
@ebz8 I've just released a new version of the library, if you uninstall your current version and re-install the latest version, does that fix the issue? 

The latest version now has the types file for the library, which your project required in order for the lightbox to work. So now that the types are supplied, it should fix the issue. 

If not, be sure to let me know and I'll work on a fix, thanks! ✅

**Comment by stephanmantler** [comment]
This problem seems to have reappeared in 1.5.9 in a slgihtly different form:

```
Type error: Could not find a declaration file for module 'lightbox.js-react'. [...]/node_modules/lightbox.js-react/dist/index.mjs' implicitly has an 'any' type.
  There are types at '[...]/node_modules/lightbox.js-react/dist/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'lightbox.js-react' library may need to update its package.json or typings.
```

**Comment by silvia-odwyer** [comment]
@stephanmantler Hi Stephan,
Thanks for letting me know about this! I've just updated the library's package.json, can you let me know if it resolves the issue?

**Comment by stephanmantler** [comment]
Hi Silvia, thank you! Yes the problem seems to be cleared up with the new package.json 🥰
