### ISSUE TITLE
HTLM Video breaks when using `magnifyingGlass`

### ISSUE THREAD

**Issue by rafavillalopez** [silvia-odwyer/lightbox.js#11]
@silvia-odwyer Hi Silvia, I've just installed the library and it works amazing. Thanks for the hardwork!

Unfortunately, I have detected the a bug when triying to use the `magnifyGlass` when the type of the item is `htmlVideo`.  It also does changes the styles of images, but it's nothing serious. 

I think the best approach would be to disable this option for this type of item, but It would be nice to be able to use it too, it's a cool feature. That's up to you. 

Thanks!

Here is a preview of the error and the code sniped that I used.  

## Code 
```JSX
      <SlideshowLightbox
        images={
          [
            {
              type: 'htmlVideo',
              videoSrc:
                'https://download-video.akamaized.net/2/playback/4baa1add-23c6-4925-afc3-755cdd8e5d67/87cf27c2-b42013aa?__token__=st=1680014437~exp=1680028837~acl=%2F2%2Fplayback%2F4baa1add-23c6-4925-afc3-755cdd8e5d67%2F87cf27c2-b42013aa%2A~hmac=a8cac410463103fe6b3fe2bf1dbdd7f0542635e6e58a2b35c84e0dcf5c438116&r=dXMtY2VudHJhbDE%3D',
            },
            {
              src: 'https://media.ambito.com/p/6b8ffa22f75de744016825151b17fe43/adjuntos/239/imagenes/038/976/0038976249/dogejpg.jpg',
              alt: 'Doge',
            },
          ]
        }
        magnifyingGlass
      />
```

## Preview
https://user-images.githubusercontent.com/80595178/228278896-edba2e13-9074-44d2-b160-7c3ccf406c67.mp4

**Comment by silvia-odwyer** [comment]
@rafavillalopez Hi Rafael,
Thanks very much for letting me know about this bug, I'll try to see if it is possible to add the magnifying glass feature to videos, but if not, I will add an update so that the magnifying glass is removed from the controls for videos.

I'll release a new version of the library with the fix for this bug, I'll let you know when it is published.

Thanks again! 😄

**Comment by silvia-odwyer** [comment]
@rafavillalopez Hi Rafael, I've just released a new version of the library which should fix this issue. The magnifying glass icon is removed for videos, as the magnifying glass unfortunately supports images only. But the icon only displays for images now ✅ 

Thanks again for letting me know about this, it's greatly appreciated! 😄 

If you have any other queries, be sure to let me know, thanks!

**Comment by rafavillalopez** [comment]
Hi @silvia-odwyer I was testing the change for the videos and It works just fine in the version  0.4.8 I think we can close this issue. 

Thanks again!
