### ISSUE TITLE
[Security Request] - Hide Key in initLightboxJS POST Request

### ISSUE THREAD

**Issue by DominikProbst** [silvia-odwyer/lightbox.js#13]
Hi Silvia,
would it be possible to hide the license key in the POST Request from initLightboxJS?
Because now someone could just copy the key and use it.
Or maybe it would be better to define on which websites the key can be used.
What do you think about that?

Thanks in advance,
Domi

**Comment by silvia-odwyer** [comment]
@DominikProbst Hi Dominik,
Thanks for this feature request, I'm just wondering if you have any preferences on how hiding the license key should be implemented? 
One option I'm thinking of is moving to NPM private packages, which will remove the need for the initLightboxJS POST request call entirely. You'll just need to install the private package using the license key and can then use the lightbox without the initLightboxJS call. That would be one potential solution to this, but do let me know your thoughts, thanks!

**Comment by DominikProbst** [comment]
@silvia-odwyer Hi Silvia,
sorry for the late reply. I forgot to answer, haha.

The NPM private package would be the fastest solution I think. 
Another solution would be to implement a system where we (the users) can define where our key can be used & the call (initLightboxJS) has to check if we are on the page. But I think that would be an overkill for this request 😅

**Comment by Mfweb** [comment]
@silvia-odwyer Are there any updates on this?

**Comment by Mfweb** [comment]
@silvia-odwyer Hello, I have already purchased a license, and the application I developed will be in a country subjected to internet censorship (which usually blocks some operator's networks). Currently, the network where the authorization server is located is on the blocklist, so customers cannot use it normally. NPM private packages could help us solve this problem. However, it seems that it is not supported at the moment. Do you have any development plans regarding this?

**Comment by JimCarnicelli** [comment]
One option would be to have a key generator that hashes your license key with the site's domain name and then you pass in that hashed value for the license key. Then you can keep your license key in your private notes. And the hashed value could only be used on that site. One could simply do this as a one-time step and paste that value into the code directly. Or alternatively, the hashing algorithm could be executed in server-side code and made available to the client, which would plug it into Lightbox.js.

**Comment by silvia-odwyer** [comment]
@Mfweb Hi there, Unfortunately Lightbox.js is only available as a public NPM package, therefore it wouldn't be available for your use case. I was hoping to add an NPM private package, however it would depend on the demand for this, so currently it's not in the development plans for now. Therefore I've just issued you with a refund in the meantime, and my apologies about this! If this changes, any future updates about this issue/feature request will be included here.

**Comment by DominikProbst** [comment]
I close this issue because I think it is done for me
