### ISSUE TITLE
Cannot open  lightbox in version `0.5.9` using props

### ISSUE THREAD

**Issue by rafavillalopez** [silvia-odwyer/lightbox.js#14]
@silvia-odwyer Hi Silvia

I recentlly installed the latest version of the libreary in my project an I'am having a some issues for my impementation using which need to display not only images but also some videos. To achieve this is using the some props: 
* `open`
* `startingSlideIndex` 
* `onClose` 
* `lightboxIdentifier` 
* `images` 
This without providing any children. 

When I try to open the lightbox changing the values provided in the props I'am getting the following error. 

![image](https://user-images.githubusercontent.com/80595178/233803173-a96e6baa-70fd-49d6-a886-7a82c12e6a7e.png)

## Implementation 

* I have a custom carousel for the view and the lightbox is open when any of the images/videos is clicked.

```ts
export const Carousel = ({ elements, containerStyle }: CarouselProps) => {
  
  const [[open, index], setSlideShowOpen] = useState([false, 0])

  useEffect(() => {
    initLightboxJS(`key`, 'team')
  }, [])

  const slideshowItems =[
    {
      src: 'https://media.ambito.com/p/6b8ffa22f75de744016825151b17fe43/adjuntos/239/imagenes/038/976/0038976249/dogejpg.jpg',
      alt: '2',
      caption: false,
    },
    {
      type: 'htmlVideo',
      videoSrc:
        'https://joy1.videvo.net/videvo_files/video/free/2014-12/large_watermarked/Raindrops_Videvo_preview.mp4',
    },
  ]

  return (
    <>
      <CustomCarousel />
      <SlideshowLightbox
        open={open}
        startingSlideIndex={index}
        onClose={() => setSlideShowOpen([false, 0])}
        images={slideshowItems}
        lightboxIdentifier="lightbox2"
        magnifyingGlass
      />
    </>
  )
}
```
* Here is the `onClick` event that triggers for any video or image inside my carousel. I just take this part of the code out to not overload the issue. 

```ts
onClick={() => setSlideShowOpen([true, elementIndex])}
```

## Preview

https://user-images.githubusercontent.com/80595178/233804201-b520dc83-3e7d-4817-bad9-a91e31b62426.mp4

Let me know if you need more info to check this error. 

Thanks.

**Comment by silvia-odwyer** [comment]
@rafavillalopez Hi Rafael, 
Thanks for letting me know about this bug, it's much appreciated! I've identified the issue and will release a fix for this, I'll let you know when the new version is published ✅

**Comment by silvia-odwyer** [comment]
@rafavillalopez I've just updated the library to include a bug fix for this. If you update your current version of Lightbox.js to the latest version, it should fix the issue. If not, just let me know, thanks!

**Comment by rafavillalopez** [comment]
@silvia-odwyer Hi Silvia, I've just updated the librabry and it is working perfectly for the implementation I have. 
Thanks!
