### ISSUE TITLE
[Feature Request]  Close the modal when clicking outside the image

### ISSUE THREAD

**Issue by khlai** [silvia-odwyer/lightbox.js#17]
Dear Silvia O'Dwyer,

Is it possible to close modal when users click outside the image?
like the [demo page](https://www.getlightboxjs.com/demo/ProductPageDemo)
thanks!

**Comment by silvia-odwyer** [comment]
@khlai Thanks for the feature request! I've just released a new version of the library which now supports this feature. If you uninstall your current version of Lightbox.js and re-install the latest version, the new functionality should be added.

To enable this feature, simply add the `modalClose` prop and set its value to `clickOutside`, like so:
```jsx
<SlideshowLightbox modalClose={"clickOutside"}>
...
</SlideshowLightbox>
```
If you have any queries, just let me know, thanks! 😄

**Comment by khlai** [comment]
That's great! thanks!
