### ISSUE TITLE
Wrapper for each image

### ISSUE THREAD

**Issue by dgastudio** [silvia-odwyer/lightbox.js#19]
hello
i need to wrap each image in custom div

    <SlideshowLightbox className="u-fl u-fl-wrap row form__row u-ml--2 u-mr--2">
      <div class="col col-3 form__col">
        <img src="https://via.placeholder.com/117X117" alt="" className={'preview'}/>
      </div>
      <div class="col col-3 form__col">
        <img src="https://via.placeholder.com/117X117" alt="" className={'preview'}/>
      </div>
      <div class="col col-3 form__col">
        <img src="https://via.placeholder.com/117X117" alt="" className={'preview'}/>
      </div>
      <div class="col col-3 form__col">
        <img src="https://via.placeholder.com/117X117" alt="" className={'preview'}/>
      </div>
    </SlideshowLightbox>

but seems not working at all, any advice?

**Comment by silvia-odwyer** [comment]
@dgastudio Hi Alexei,
Thanks for opening this issue, I'd be glad to help! To wrap images in custom divs, a data attribute needs to be added to each image; additionally, a `lightboxIdentifier` prop needs to be added to the SlideshowLightbox component, like so:

```
<SlideshowLightbox lightboxIdentifier="lightbox1">
  <div class="col col-3 form__col">
    <img src="https://via.placeholder.com/117X117" data-lightboxjs="lightbox1" alt="" className={'preview'}/>
  </div>
  . . .
</SlideshowLightbox>
```

The value of the data attribute should be the same for each image, and it should match the value of the `lightboxIdentifier` prop.

Hopefully that helps, and let me know if you have any queries ✅

**Comment by dgastudio** [comment]
Hello @silvia-odwyer 
thank you very much, it works now
