### ISSUE TITLE
[Feature Request] Props for SlideshowLightbox also for Image Component

### ISSUE THREAD

**Issue by annarack** [silvia-odwyer/lightbox.js#24]
Can we have the same properties for the Image component like the ones for the SlideshowLightbox? At least the ones that make sense, like:

showFullScreenIcon={false}
fullScreen={true}
modalClose={"clickOutside"}

Thanks for your work btw! :)

**Comment by silvia-odwyer** [comment]
@annarack I've updated the library, and it now includes new props for the Image component, which were previously only available for the SlideshowLightbox component. These include props such as `modalClose`, `fullScreen` and so forth. It's available as part of the latest version release on NPM.
