### ISSUE TITLE
Close modal on click on backdrop

### ISSUE THREAD

**Issue by dgastudio** [silvia-odwyer/lightbox.js#27]
right now, there are only 2 ways to open the opened modal
- by clicking on small X in top right side
- by pressing ESC

I think adding click on backdrop to close the modal, can be helpful

In addition, the sidebar arrows can easily be expanded to make them easier to click.

![CleanShot 2023-08-04 at 17 47 15@2x](https://github.com/silvia-odwyer/lightbox.js/assets/161524/673b0108-94f3-485d-814b-e74535e37d09)

**Comment by silvia-odwyer** [comment]
@dgastudio Hi Alexei,
Currently, it's possible to close the modal when the backdrop is clicked by setting the `modalClose` prop to "clickOutside". 

```jsx
<SlideshowLightbox modalClose={"clickOutside"}>
...
</SlideshowLightbox>
```
With this addition, the lightbox will close whenever the outside of the image is clicked.

That's a good point about expanding the clickable area of the sidebar arrows. I'll work on adding this to the lightbox and will let you know when a new version of the library is published.

**Comment by dgastudio** [comment]
Thank you very much @silvia-odwyer
