### ISSUE TITLE
Use different image sizes

### ISSUE THREAD

**Issue by dgastudio** [silvia-odwyer/lightbox.js#28]
Dear @silvia-odwyer
As far as I can see (based on your demos), right now your awesome plugin is using the same image for both sizes, thumbnails (e.g. in a grid) and full view.

this is not the best solution in terms of performance and traffic.

Maybe you have any solutions, or maybe plans to add different image sources for full/thumbnail views? Maybe based on data-attribute?
something like
<img src={thumbnail_image_url} data-lightbox-src={full_image_url}/>

![CleanShot 2023-08-09 at 19 45 08@2x](https://github.com/silvia-odwyer/lightbox.js/assets/161524/ed847f05-3ab5-4ede-88b1-78a018e9312d)

thank you

**Comment by silvia-odwyer** [comment]
@dgastudio Hi Alexei, Thanks for this feature request! That's a great point about specifying different image sizes for the thumbnails (outside the lightbox) and lightbox images. 

Currently, it's only possible to specify different image sizes with the `images` prop, so I will add new functionality where the original image size can be specified through a data attribute instead.

I'll let you know when a new version of the library is published with the update ✅

**Comment by silvia-odwyer** [comment]
@dgastudio I've just updated the library to include this new feature, it's part of the latest version release.

You can specify the source link of the high-resolution, original image source with the `data-lightboxjs-original` data attribute, and this will be displayed in the lightbox. The optimized, thumbnail image could then be used to render the image outside the lightbox. Here's a JSX sample:
```jsx
<SlideshowLightbox lightboxIdentifier="lightbox1" showLoader={true}>
  <img
     src={"https://source.unsplash.com/EJpe9XZwBhU/850x500"}
     alt={"A blue sky overlooking green hills and trees"}
     data-lightboxjs-original={"https://source.unsplash.com/EJpe9XZwBhU/1700x1000"}
     data-lightboxjs="lightbox1"
  />
</SlideshowLightbox>
```

**Loading indicator**
If you'd like to display a loading indicator while the original image is loading, then just set the `showLoader` prop to `true`.

**Images prop**
Just adding this for documentation purposes, in case anyone visits this issue in the future:
If you're using the `images` prop, then you can add different image sizes by adding an `original` property to each image object. More details with a code sample is included [here](https://github.com/silvia-odwyer/lightbox.js/issues/1#issuecomment-1246035050).

-----
Thanks again for this great feature request. If you would like changes to this or have any edits you'd like me to make, just let me know.

**Comment by dgastudio** [comment]
@silvia-odwyer you are awesome!
thank you very much
P.S. Licence purchased!

**Comment by silvia-odwyer** [comment]
@dgastudio Glad to help! If you have any other feature requests, just let me know, I'm always striving to improve this library however I can. ✅
