### ISSUE TITLE
Callback when next/previous image is selected

### ISSUE THREAD

**Issue by andreisocaciu** [silvia-odwyer/lightbox.js#29]
Hi, 

I want to display additional information on top of the image preview, but can't find a way to know which image is rendered. I saw that through the render.imgSlide prop I could render something different from what this library is rendering, but then I would be losing all the good stuff from the default renderer (zoom, fullscreen styles, etc).

How can we solve this issue?
1. One solution would be to have 2 new props:
```
onNext: (currentImage: ImageType) => void
onPrevious: (currentImage: ImageType) => void
```
that I could use to save this information in my own state.

2. Enhance the `render.imgSlide` prop function to receive a `defaultElement` so one could to this:
```
<SlideshowLightbox
  ...
  render={{
    imgSlide(image: ImageType, defaultElement: React.ReactElement) {
      return (
        <>
         {defaultElement}
          <div style={{ position:'fixed', bottom: 0, right: 0 }}>{image.caption}</div>
        </>
    }
  }}
/>
```

**Comment by andreisocaciu** [comment]
Do you have a timeline for when I can expect a release with these changes?

**Comment by silvia-odwyer** [comment]
@andreisocaciu Hi Andrei, 
I'm planning on adding the `onNext` and `onPrev` event emitters to the library, so that when a new image is selected, the event will emit the index of the newly selected image along with its metadata. That way, you can then display your custom information in the lightbox.

I should have this functionality ready by tomorrow, I will also let you know when it's published ✅ 😄

**Comment by silvia-odwyer** [comment]
@andreisocaciu I've published a new version of the library, which contains the new functionality. 

The new props are:
- **onNext**: -> returns (index, imageMetadata)
- **onPrev**: -> returns (index, imageMetadata)

If you'd like to get the initial slide value when the lightbox opens, the `onOpen` event now returns the image index, along with the image metadata too:
- **onOpen**: -> returns (index, imageMetadata)

Here's a quick example:
```jsx
<SlideshowLightbox 
onOpen={(index, imgMetadata) => {console.log("onOpen -> Index and image metadata: ", index, imgMetadata)}}
onNext={(index, imgMetadata) => {console.log("onNext -> Index and image metadata: ", index, imgMetadata)}}
onPrev={(index, imgMetadata) => {console.log("onPrev -> Index and image metadata: ", index, imgMetadata)}}>
...
</SlideshowLightbox>
```

Hopefully that helps, and let me know if have any feature requests. Thanks!
