### ISSUE TITLE
You don't answer the messages I sent through your website

### ISSUE THREAD

**Issue by menashkes** [silvia-odwyer/lightbox.js#3]
I purchased the product

The code is not working

I want a refund ASAP

Please check your messages from the website

Thanks

**Comment by silvia-odwyer** [comment]
@menashkes Hi there! 

I have just issued you a full refund. 😄

I did indeed receive your message sent through the form approximately two hours ago, and I always aim to get back to any developers that contact me through the form or create issue requests here as soon as I can. ✅ I love to help out other developers with setting up the lightbox or through implementing feature requests/bug patches, so while it's a pity that I couldn't help you setup the lightbox in this particular instance, I've just issued a full refund.

I would like to apologise for any inconvenience caused. If you have any other queries, don't hesitate to let me know. Thanks!

**Comment by menashkes** [comment]
Thank you dear

Appreciate your quick response (I guess quick is relative) :)

------- Original Message -------
