### ISSUE TITLE
Next.js can't slide images on build or production.

### ISSUE THREAD

**Issue by 3enzkung** [silvia-odwyer/lightbox.js#33]
Bugs in next.js, i can not slide images on my project for npm run build. It work in dev project but not in build project.

See this video in link beblow:
https://watch.screencastify.com/v/8wAQMettdGqDz9hhoOiX

**Comment by silvia-odwyer** [comment]
@3enzkung Hi there,
Thanks for letting me know about this bug, I'm going to debug this issue. 

Could you provide a code sample so that I can recreate the issue? Also, it would also be useful too if you could provide the version numbers of Next.js and React that your project is using. Thanks!

**Comment by 3enzkung** [comment]
> @3enzkung Hi there, Thanks for letting me know about this bug, I'm going to debug this issue.
> 
> Could you provide a code sample so that I can recreate the issue? Also, it would also be useful too if you could provide the version numbers of Next.js and React that your project is using. Thanks!

"next": "13.4.13",
"react": "18.2.0",

**Comment by silvia-odwyer** [comment]
@3enzkung Just wondering if you're using the latest version of Lightbox.js? I've tried creating an example Next.js app using the versions you provided, and the drag-to-swipe functionality is working in production. If you still get the bug, can you provide an example project where the error is occurring, as it would help me for debugging.

**Comment by 3enzkung** [comment]
> @3enzkung I'm wondering if you're using the latest version of Lightbox.js? I've tried creating an example Next.js app using the versions you provided, and the drag-to-swipe functionality is working in production. If you still get the bug, can you provide an example project where the error is occurring, as it would help me for debugging.

My project upload to my vps (ubuntu 18)  with command "pm2 start mysite" and test in site url "https://mysite.com", drag-to-swipe functionality is not working.

It Working in PC not VPS, run with command "npm run build"  and "npm run start", and test with url: http://localhost:3000 = working, but not woking on https://mysite.com

I test your code, yes it is not working.
```
<SlideshowLightbox lightboxIdentifier="lightbox1" framework="next" images={images}>
        {images.map((image) => (
            <Image
              src={image.src}
              alt={image.alt}
              height={500}
              width={500}
              data-lightboxjs="lightbox1"
              quality={80}
            />
        ))}
</SlideshowLightbox>
``` 

And is my code.
```
<SlideshowLightbox
            showThumbnailIcon={false}
            showFullScreenIcon={false}
            showSlideshowIcon={false}
            showThumbnails
            modalClose="clickOutside"
            lightboxIdentifier={`lbx${index + 1}`}
            framework="next"
            images={getSrc.map((data) => ({
              src: data.src,
              alt: data.alt,
              caption: data.alt,
            }))}
          >
            {Parser(description, {
              replace: (domNode) => {
                if (
                  domNode.attribs &&
                  domNode.attribs.src &&
                  !domNode.attribs.src.match(/(cdn.ckeditor).*/)
                ) {
                  return (
                    <Image
                      src={domNode.attribs.src}
                      alt={domNode.attribs.alt}
                      title={domNode.attribs.alt}
                      height={500}
                      width={500}
                      data-lightboxjs={`lbx${index + 1}`}
                      quality={80}
                      className="object-contain w-auto h-auto inline-block"
                    />
                  );
                }
              },
            })}
          </SlideshowLightbox>
``` 

My English isn’t good.

**Comment by silvia-odwyer** [comment]
@3enzkung I've deployed a test app on Netlify here, and the drag-to-swipe seems to be working: https://next-lightboxjs-test.netlify.app/ 
What version of Lightbox.js are you using? Make sure that you're using the latest version 👍

**Comment by silvia-odwyer** [comment]
@3enzkung I would need an example project that reproduces the error. Can you create a minimum example repository and link it to me? If it just has the page with the lightbox code, and the package.json, next.config.json etc, that's all it would need.

That way, I can see what's causing the issue for your specific use case. Unfortunately I have no way to debug this unless I have a project which reproduces the error. It would be greatly appreciated, as I'd like to get this issue fixed. ✅

**Comment by 3enzkung** [comment]
> @3enzkung I would need an example project that reproduces the error. Can you create a minimum example repository and link it to me? If it just has the page with the lightbox code, and the package.json, next.config.json etc, that's all it would need.
> 
> That way, I can see what's causing the issue for your specific use case. Unfortunately I have no way to debug this unless I have a project which reproduces the error. It would be greatly appreciated, as I'd like to get this issue fixed. ✅

After update this version 0.8.7 of lightbox.js-react, it working. Thank you.

**Comment by silvia-odwyer** [comment]
> After update this version 0.8.7 of lightbox.js-react, it working. Thank you.

@3enzkung I'm glad the recent update of the library has fixed the issue for Next.js. ✅
