### ISSUE TITLE
Passing classes to lightbox container and images seems broken

### ISSUE THREAD

**Issue by dandc11** [silvia-odwyer/lightbox.js#34]
Hi @silvia-odwyer, 

After updating my version to 0.8.3, it seems the CSS classes are no longer making it into the component. When I lift the tutorial example from the website and plug it into my Next.js 13 app, neither the classname value on SlideshowLightbox nor the classname values on any of the images are making onto the elements rendered by the component, which otherwise works fine. 

![image](https://github.com/silvia-odwyer/lightbox.js/assets/34725981/3610a680-55e9-4451-88f7-917e4f1c5b1c)

Though I can't tell that it ever made it into the official documentation, there was for a time a prop called `lightboxImgClass` which allowed for passing a class to the feature image in the lightbox.

**Comment by silvia-odwyer** [comment]
@dandc11 Hi Dan,
Thanks for letting me know about this bug, I've identified what was causing the issue. If you update to the latest version of Lightbox.js, the issue should be fixed. The `lightboxImgClass` and `className` properties should now be working again. ✅

**Comment by dandc11** [comment]
@silvia-odwyer, it looks good to me now. Thanks once again.
