### ISSUE TITLE
startingSlideIndex prop does not work as expected

### ISSUE THREAD

**Issue by andreisocaciu** [silvia-odwyer/lightbox.js#36]
I'm trying to open the lightbox slideshow at a certain index of the images array, but it always opens at index 0.

**Comment by silvia-odwyer** [comment]
@andreisocaciu Hi Andrei,
Thanks for opening this issue. Could you provide a code sample, so that I can recreate the bug? This will help me to see what's causing the issue specifically so that I can implement a fix for this.

**Comment by andreisocaciu** [comment]
[Here](https://codesandbox.io/p/sandbox/lightbox-issue-30-forked-2ss8l6) you can see that it opens the correct index the first time it loads, but since the `useEffect` – that checks if `props.startingSlideIndex` is passed in – is dependent only on the `open` prop, it doesn't rerun if `startingSlideIndex` changes. You need to change this snippet to see this happing:

```
<button
  onClick={() => {
    photoSetter(3); // here change this index to anything else and the slideshow will open with the original index, unless page is refreshed
  }}
>
```

**Comment by silvia-odwyer** [comment]
@andreisocaciu Thanks for the CodeSandbox link! I've just released a new version of the library, which includes a fix for the issue. I've added a dependency on the `startingSlideIndex` prop in the `useEffect` code in order to get its newly updated value.

**Comment by andreisocaciu** [comment]
In the codesandbox example it works, but for my use case it breaks in another place. 
`images` is an `[]` (empty array), so `slideIndex` is computed as `NaN`, and then `props.image[slideIndex].caption` breaks.

Stack trace:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'caption')
    at isImageCaption (index.modern.js:296:1).
```

**Comment by silvia-odwyer** [comment]
@andreisocaciu Thanks for letting me know about this! I've added a check for an empty `images` array, and just released a new version. Let me know if it solves the issue.

**Comment by andreisocaciu** [comment]
Could you please release a new version with these changes? I tried deploying, but Vercel doesn't seem to apply the patch properly.

**Comment by silvia-odwyer** [comment]
@andreisocaciu I've added the first change (for the `isImageCaption` function) above. It hasn't been published yet though, as I have a note regarding the second change. 

For the second change, if I add the `images` depdendency to the useEffect code, this will run the useEffect function each time an image is swiped. The `images` array is updated each time an image is loaded, thus it would trigger the useEffect to run.

I could add a dependency to `props.images` instead, would that work for your use case?

**Comment by andreisocaciu** [comment]
It works if the `useEffect` is using the `props.images` instead of the `useState` ones. But maybe this will break other use cases where images are passed as children. 

The version where you'd add the `props.images` as dependency won't work because the state `images` are still the ones from the previous render before the `initImages` useEffect had run (an array with length 0) and the first image is opened in the viewer, not the one I specified in `startingSlideIndex`.

```diff --git a/node_modules/lightbox.js-react/dist/index.modern.js b/node_modules/lightbox.js-react/dist/index.modern.js
index 0a95e8b..d4625d8 100644
--- a/node_modules/lightbox.js-react/dist/index.modern.js
+++ b/node_modules/lightbox.js-react/dist/index.modern.js
@@ -31,6 +31,10 @@ function _extends() {
 var styles = {"lightboxjs":"_30i9K","slideshowContainer":"_3kSzL","slideshowBtn":"_tCjNO","closeIcon":"_2IJEr","iconsHeader":"_2Yv4j","prev1":"_1lgEi","next1":"_DDceb","icon":"_2Vept","prevIcon":"_2gxOL","nextIcon":"_3gp2w","show":"_2crlL","displayHidden":"_34QvR","thumbnail":"_1R214","hoverShadow":"_3EuZy","thumbnails":"_3pfLz","thumbnailsWithCaption":"_Fp_rP","imageSlide":"_22ETc","thumbnailsOuterContainer":"_-wN_b","videoThumbnailsOuterContainer":"_KbOLW","imgTitleContainer":"_1j-pZ","thumbnailsAndCaption":"_1nxK_","htmlVideoOuterContainer":"_z-jNd","caption":"_2jJU2","galleryImg":"_lY1R_","slideshowAnimContainer":"_wTR3b","fullScreenContainer":"_11N04","imageInnerContainer":"_20Hp6","magnifyWrapper":"_3PObS","slideshowInnerContainer":"_1JRT_","slideshowInnerVideoContainer":"_1ni2w","slideshowInnerContainerThumbnails":"_GV0NM","lightboxContainer":"_3BNPD","slideshowAnimImg":"_j1nqC","controls":"_ABXHD","ytVideo":"_2eq8V","videoOuterContainer":"_1P3Wc","customVideoContainer":"_Aq8HC","videoIconsHeader":"_qtY0U","lightbox":"_3cxVN","imgTitle":"_2pA2G","lightbox_img":"_3A0RO","slideshow_img_fullscreen":"_2yYOi","slideshowInnerContainerFullScreen":"_hWNoE","fullScreenLightboxImg":"_1ek8k","opacity-fade":"_2P48G","imageSliderThumbnails":"_1xBL9","slideshow_img":"_1yWyS","light_icon":"_1kIQ4","dark_icon":"_1qbJe","light_header_icon":"_3DIHj","dark_header_icon":"_11aT5","magnifier-image":"_mdJQi","active":"_3sodH","inactiveThumbnailBorder":"_3bkUp","embla_thumbs":"_32vVi","htmlVideo":"_sqvn-","react-transform-component":"_3Id1-","loader":"_3qqrl","rotation":"_1hUzk","day_loader":"_1itZw","night_loader":"_2TI_i","closeButton":"_2kumA","slideImageAndCaption":"_238y5","roundedBorder":"_2FvXV","maxWidthFull":"_oa5b0","maxWidthWithoutMagnifier":"_z-bHV","lightboxVideo":"_hGbhv","navigation-wrapper":"_1dVqh","dots":"_3MuXE","dot":"_3U2py","arrow":"_35l6Q","leftArrow":"_1I4Zg","rightArrow":"_1lqBv","arrow--disabled":"_37Xda","navDotsMargin":"_1LtID","inactiveThumbnailBorderImgSlider":"_2y9OU","ytVideoImgSlider":"_2oAIc","outerYTVideoImgSlider":"_2-c5L","imgSliderArrow":"_1Bey-","cursorPointer":"_3xuz3","lightboxjs_icon":"_1fpgA","embla":"_1cifY","embla__viewport":"_1mBUR","embla__container":"_Bqct9","embla__slide":"_1eJNe","embla_thumbs__viewport":"_1tmVU","embla_thumbs__container":"_3-Y1e","embla_thumbs__slide":"_jp0uN","embla_thumbs__slide__img":"_3S-ie","mlAuto":"_1afvv"};
 
 var wrapNums = function wrapNums(minNum, maxNum, v) {
+  if (minNum == maxNum) {
+    return minNum;
+  }
+
   var rangeSize = maxNum - minNum;
   return ((v - minNum) % rangeSize + rangeSize) % rangeSize + minNum;
 };
@@ -294,7 +298,7 @@ var SlideshowLightbox = forwardRef(function (props, ref) {
   };
   var isImageCaption = function isImageCaption() {
     if (props.images && props.images.length > 0) {
-      if (props.images[slideIndex].caption) {
+      if (props.images[slideIndex]?.caption) {
         return true;
       }
     }
@@ -1318,13 +1322,13 @@ var SlideshowLightbox = forwardRef(function (props, ref) {
   }, [props.images, props.displayedImages]);
   useEffect(function () {
     if (props.open) {
-      var starting_index = wrapNums(0, images.length, props.startingSlideIndex);
+      var starting_index = wrapNums(0, props.images.length, props.startingSlideIndex);
       setStartingIndex(starting_index);
       openModalWithSlideNum(starting_index);
     } else if (props.open == false) {
       closeModal();
     }
-  }, [props.open, props.startingSlideIndex]);
+  }, [props.open, props.startingSlideIndex, props.images]);
   useEffect(function () {
     if (isOpen == true) {
       dispatchOpenEvent();
```

**Comment by silvia-odwyer** [comment]
@andreisocaciu Hi Andrei,
I've just updated the library to resolve this issue. That's a great point about supporting all use cases, not just `props.images`, and I wanted to add the `images` dependency to the useEffect code instead. I've added a check to the useEffect, which has a custom check if the `images` array has changed or not, and excludes the loading prop from the check. That way, the `images` dependency can be added to the useEffect instead.

Let me know if it solves your issue, and if not, I will debug further.

**Comment by andreisocaciu** [comment]
I get this error if I try to open the slideshow now. (`v0.9.3`)

You need to check if `typeof object1 === 'object' && object1 != null` because `typeof null === 'object'` (Javascript, amirite? 😅)

```
Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at areObjectsEqual (index.modern.js:1339:1)
    at eval (index.modern.js:1340:1)
    at Array.every (<anonymous>)
    at areObjectsEqual (index.modern.js:1339:1)
    at imagesEqualToPrevious (index.modern.js:1365:1)
    at eval (index.modern.js:1378:1)
  ```

**Comment by silvia-odwyer** [comment]
@andreisocaciu I've just updated the function to check that neither object is equal to null. Thanks for that! That's how it goes in the Javascript world I guess 😅

**Comment by andreisocaciu** [comment]
Issue is now fixed. Thanks a lot!
