### ISSUE TITLE
Caption?

### ISSUE THREAD

**Issue by yapjinkun** [silvia-odwyer/lightbox.js#40]
Is this support caption? I saw there's a captionStyle props but how does it works? I need to display text for the image.

**Comment by silvia-odwyer** [comment]
@yapjinkun Yes, it's possible to include an image caption underneath each image in the lightbox.

This is possible through adding the caption property to an image object in an array of images. This would then be passed to the lightbox as shown in the next step below.
```js
const images = [
  {
    src: 'https://source.unsplash.com/sQZ_A17cufs/549x711',
    alt: 'Mechanical keyboard with keycaps.',
    caption: 'Here's an example of a mechanical keyboard',
  },
  ...
]
```

You would then need to pass the images array to the `images` prop in the `SlideshowLightbox` component:
```jsx

<SlideshowLightbox images={images} lightboxIdentifier="lbox">
    {images.map((image) => (
        <img data-lightboxjs="lbox" src={image.src} alt={image.alt} />   
    ))}

</SlideshowLightbox>
```

If you are using Next.js, there is some additional configuration required, which is shown in the [guide here](https://www.getlightboxjs.com/docs/nextjsguide/). Hopefully that helps, and let me know if you have any queries.

**Comment by yapjinkun** [comment]
thank you, i got it worked.
