### ISSUE TITLE
SlideshowLightbox, missing classname in case there are only one photo

### ISSUE THREAD

**Issue by dgastudio** [silvia-odwyer/lightbox.js#46]
My code
![CleanShot 2024-01-13 at 14 42 40@2x](https://github.com/silvia-odwyer/lightbox.js/assets/161524/7c7ccf7a-7e54-4155-b93e-519a3f2d334e)

render in case of one photo
![CleanShot 2024-01-13 at 14 43 11@2x](https://github.com/silvia-odwyer/lightbox.js/assets/161524/700de480-ff08-4838-a321-a2351e75ac97)

render in case of multiple photos
![CleanShot 2024-01-13 at 14 43 39@2x](https://github.com/silvia-odwyer/lightbox.js/assets/161524/f76eb00c-b2e3-4368-8703-07e4cfc6dd31)

so, as you can see, in case of only one photo, classname is not applied

**Comment by silvia-odwyer** [comment]
@dgastudio Hi Alexei,
Thanks for letting me know about this bug! I've fixed the issue and published a new version of the library, which should rectify the bug. Hopefully that helps, and let me know if you have any queries.
