### ISSUE TITLE
The onerror function is not reachable using lightbox.js

### ISSUE THREAD

**Issue by yamilelias** [silvia-odwyer/lightbox.js#47]
# Context
We started using the lightbox.js on our project since it simplifies how to display the images. However, we can't launch it to production since we can't manage the errors on the attachments. Our project relies on a third-party API to show media, but sometimes that media is unavailable, and we need to refetch. Right now, since we can't access the onError property, we can't make that refetch, hence making it impossible for us to implement the lightbox.js library.

# System specs
- **License type**: Team
- **Project**: Next.js
- **Nodejs**: `v20.11.0`

# What is missing?
- Make accessible the `onerror` callback for `img` or `video` inside Lightbox.js
- The onerror callback could be part of the images items list you pass to the slidebox component

**Comment by silvia-odwyer** [comment]
@yamilelias Thanks very much for this feature request, I'll get started on adding support for passing the onError callback to images in the lightbox. I'll let you know when the new version of the library is published containing the new feature. ✅

**Comment by silvia-odwyer** [comment]
@yamilelias I've just published a new version of the library, which contains an `onImgError` event handler.

The prop is:
 - **onImgError**: -> returns (event, imageMetadata, index)

Here's an example:
```jsx
<SlideshowLightbox 
onImgError={(event, imgMetadata, index) => {console.log("onImgError -> ", event, index, imgMetadata)}}>
...
</SlideshowLightbox>
```
When an error occurs in fetching the image, the onImgError callback will return the event object, image metadata and index of the image.

Hopefully that helps, and let me know if you have any queries.
