### ISSUE TITLE
4 moderate severity vulnerabilities????

### ISSUE THREAD

**Issue by Stefano191** [silvia-odwyer/lightbox.js#5]
Upon installing i get 4 vulnerabilities:

![image](https://user-images.githubusercontent.com/29723844/209992387-ca9a14f7-bd17-4545-a230-6fa1bf762978.png)

Fix please :)

**Comment by kane007** [comment]
For now I fixed by overriding postcss-functions in my package.json file:
` "overrides": {
        "postcss-functions": "4.0.2"
    },`

**Comment by silvia-odwyer** [comment]
This was due to a dependency on the postcss7-compat version of Tailwind CSS. However Lightbox.js no longer uses this library, so the vulnerabilities are no longer present. Thus I will close this issue.
