### ISSUE TITLE
initLightboxJS() causing these terminal errors

### ISSUE THREAD

**Issue by iriepixel** [silvia-odwyer/lightbox.js#52]
Hi @silvia-odwyer ,

I just purchased the licence, but I'm experiencing an issue with our Shopify Hydrogen Remix project.

This happens when I try to init the Lightbox with `initLightboxJS()`. Do you have any ideas on how to fix that? Thank you!

Please see the screenshot attached:

![CleanShot 2024-04-16 at 12 25 56](https://github.com/silvia-odwyer/lightbox.js/assets/6594989/5154cab5-d1f6-4174-a6bd-b9d280eb9e04)

```
useEffect(() => {
    initLightboxJS('license', 'team');
  }, []);
```

```
"engines": {
    "node": ">=18.0.0"
  }
```

It would be great to understand what's happening here.

**Comment by silvia-odwyer** [comment]
@iriepixel Hi Jev,
It appears that the issue you're experiencing is related to the issue mentioned on the [Shopify forums here](https://community.shopify.com/c/shopify-apps/the-package-quot-crypto-quot-wasn-t-found-on-the-file-system-but/td-p/2336807). It appears to be related to Cloudflare Workers being used by Oxygen, thus it isn't a Node.js environment. 

To solve the issue, then be sure to try out the solution mentioned in the issue linked above. Hopefully that helps, and let me know if you have any queries.
