### ISSUE TITLE
a useless element 1 appears in the DOM

### ISSUE THREAD

**Issue by sun0225SUN** [silvia-odwyer/lightbox.js#55]
When I set the Image Animation to fade, a useless element 1 appears in the DOM. I think this is a problem.

<img width="1680" alt="image" src="https://github.com/user-attachments/assets/7ebdf31c-10d8-496c-abb8-218b18ab07c6">

**Comment by silvia-odwyer** [comment]
@sun0225SUN Hi Guoqi,
I've just released a new version of the library which should solve the issue. If you uninstall your current version and install the latest version, the issue should be fixed.

**Comment by sun0225SUN** [comment]
Thanks, it's cool now
