### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by DominikProbst** [silvia-odwyer/lightbox.js#6]
Hi, 
I've got some feature requests I would like to have built in. :-)
I'm using NextJS FYI.

1. Disable one or more controls. At the moment only all or none is possible
2. Disable zooming / pinching / etc. on the image. So I can just show the normal image without any extras
3. I would be nice to change the image by using the keyboard arrows or while dragging them to the side with the mouse
4. I would like to change the icons of the arrows 

Thank you!

**Comment by silvia-odwyer** [comment]
@DominikProbst Hi Dominik, Those are some excellent feature requests, I will get working on these right away. ✅ 
I'll let you know when a new version of the library is released containing these features, along with any new props required for the features.

**Comment by silvia-odwyer** [comment]
@DominikProbst Hi Dominik, 
I've just implemented the first three features mentioned above. These updates are now available as part of the latest version release of the library. ✅ 

With regards the fourth feature about custom arrow icons, I'd just like to know what type of icons you would like to change the arrows to. For instance, would you like to use FontAwesome icons, or icons from other libraries? Or would you like to replace the arrows with another text character? I can implement this feature once I know what type of arrow icons you would like supported.
 
**1 . Disable one or more controls**
New props have been added to hide/show the relevant controls. If you no longer wish to display a particular icon in the controls, just set the relevant prop to `false`. 

Here are the props:
- showFullScreenIcon
- showThumbnailIcon
- showSlideshowIcon
- showMagnificationIcons

For example, the following will hide the zoom controls, along with the slideshow playback icon:
```jsx
<SlideshowLightbox showMagnificationIcons={false} showSlideshowIcon={false}>
...
</SlideshowLightbox>
```

**2 . Disable zooming**
You can disable zooming/panning functionality by setting the `disableImageZoom` prop to `true`:
```jsx
<SlideshowLightbox disableImageZoom={true}>
...
</SlideshowLightbox>
```

This will automatically remove the magnifying glass icons from the icon controls also.

**3 . Keyboard Navigation**
Keyboard navigation functionality is now supported. You can navigate from image to image by pressing the right and left arrow keys. You can also close the lightbox by pressing the `Escape` key.

Hopefully that helps, and let me know if you have any questions or queries. Thanks! 😄

**Comment by silvia-odwyer** [comment]
@DominikProbst Hi Dominik, I've just added two new props where you can pass custom icon components to the lightbox. This feature is part of the latest version release of the library.

These props are:
- prevArrow
- nextArrow

Here's a quick example:
```jsx
<SlideshowLightbox prevArrow={<PrevArrowIcon />} nextArrow={<NextArrowIcon />}>
...
</SlideshowLightbox>
```

Let me know if you have any queries, bugs to report, or feature requests; thanks very much!

**Comment by DominikProbst** [comment]
Thank you very much!! :-)
