### ISSUE TITLE
Single-Image component is missing

### ISSUE THREAD

**Issue by stephanmantler** [silvia-odwyer/lightbox.js#63]
It appears the [Image component](https://www.getlightboxjs.com/docs/Image/) to display a single image is missing from the codebase. The examples on that page are broken, too (broken images).

**Comment by silvia-odwyer** [comment]
@stephanmantler Hi Stephan,
Thanks for opening this issue. The library has been updated to now include the Image component. I've also updated the documentation too so that the demos run again. ✅

**Comment by stephanmantler** [comment]
Thank you! That was exactly the use case I was looking for.
