### ISSUE TITLE
thumbnailBorder & iconColor don't apply properly

### ISSUE THREAD

**Issue by JaredPage** [silvia-odwyer/lightbox.js#7]
Simply using the example from the documentation, but adding the `iconColor` & `thumbnailBorder` classes results in the icons and thumbnail border......not actually changing color. It seems the CSS has been put in the wrong order, the `.dark_header_icon svg` class overrides the 'red' that I have set below:  

```js
<SlideshowLightbox
      iconColor="red"
      thumbnailBorder="red"
      showThumbnails={true}
      className='container grid grid-cols-3 gap-2 mx-auto'>

      <img className='w-full rounded' src='https://images.pexels.com/photos/580151/pexels-photo-580151.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2' />
      <img className='w-full rounded' src='https://images.pexels.com/photos/13996896/pexels-photo-13996896.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2' />
      <img className='w-full rounded' src='https://images.pexels.com/photos/13208323/pexels-photo-13208323.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2' />

</SlideshowLightbox>
```

```css
.dark_header_icon svg {
    background-color: transparent;
    color: #626b77;
}
```

It seems that the values in, at least, `iconColor` simple get added to the element at the root level
```html
<section class="iconsHeader imageModal dark_header_icon" style="color: red;">
```
 which causes the more specific CSS class to override it. This means to actually set thumbnail border and icon colors, manual CSS overriding needs to be done for this functionality to work. 
 
 Tested in Chrome & Safari.

**Comment by silvia-odwyer** [comment]
@JaredPage Hi Jared, thanks for letting me know about this! I'll get working on a fix for this issue right away ✅

**Comment by JaredPage** [comment]
> @JaredPage Hi Jared, thanks for letting me know about this! I'll get working on a fix for this issue right away ✅

Thanks for the quick reply Silvia!

**Comment by silvia-odwyer** [comment]
@JaredPage Hi Jared, 
I've just fixed this bug, the issue should now be resolved. 

It's available as part of the latest version release of the library, so if you uninstall your current version and re-install the latest version, it should be fixed. 

However, if not, be sure to let me know so I can take a look.

**Comment by JaredPage** [comment]
Amazing @silvia-odwyer! I can verify that both of these properties now work correctly. Thanks!
